card = [
    "tarot-fool.jpg",
    "tarot-magician.jpg",
    "tarot-highpriestess.jpg",
    "tarot-empress.jpg",
    "tarot-emperor.jpg",
    "tarot-hierophant.jpg",
    "tarot-lovers.jpg",
    "tarot-chariot.jpg",
    "tarot-strength.jpg",
    "tarot-hermit.jpg",
    "tarot-wheeloffortune.jpg",
    "tarot-justice.jpg",
    "tarot-hangedman.jpg",
    "tarot-death.jpg",
    "tarot-temperance.jpg",
    "tarot-devil.jpg",
    "tarot-tower.jpg",
    "tarot-star.jpg",
    "tarot-moon.jpg",
    "tarot-sun.jpg",
    "tarot-judgement.jpg",
    "tarot-world.jpg"
]

tarot = [
    "    0 - The Fool",
    "    I - The Magician",
    "   II - The High Priestess",
    "  III - The Emperess",
    "   IV - The Emperor",
    "    V - The Hieropahnt",
    "   VI - The Lovers",
    "  VII - The Chariot",
    " VIII - Strength",
    "   IX - The Hermit",
    "    X - Wheel Of Fortune",
    "   XI - Justice",
    "  XII - The Hangedman",
    " XIII - Death",
    "  XIV - Temperance",
    "   XV - The Devil",
    "  XVI - The Tower",
    " XVII - The Star",
    "XVIII - The Moon",
    "  XIX - The Sun",
    "   XX - Judgement",
    "  XXI - The World"
]
